---
title: "linear regression"
author: "Wang,Liuying"
date: "2018年3月5日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
新建Rmd之后有很多文字，修改最上面YAML块（控制标题作者等信息）和上面这个代码块，其它删掉

白色的地方可以随意写字
# simulation 井号后面跟字，表示标题
```{r}
#代码块，用ctrl+alt+I 就能创建一个灰色区域，里面写代码
#不用复制结果过来，knit的时候会自动输出结果
library(MASS)
dataGene = function(n = 100,Xmean = 2, Xsd = sqrt(2), emean = 0, esd = sqrt(2))
{
  X = mvrnorm(n, mu = c(1,1), Sigma = matrix(c(2,1,1,2),ncol = 2))
  e = rnorm(n,mean = emean,sd = esd)
  Y = 2+3*X[,1]+1.5*X[,2]+e
  return (list(X = X, Y = Y))
}

data = dataGene()
par(mfrow = c(1,2))
plot(data$X[,1],data$Y)
plot(data$X[,2],data$Y)


fit = lm(Y~X,data = data)
fit$coefficients
```

#simulation 1000次
模拟1000次，可以看出估计值的均值和中位数都比较接近真实
```{r}
results = replicate(n = 1000,
                    {data = dataGene()
                    fit = lm(Y~X, data = data)
                    return (fit$coefficients)})
#均值
apply(results,1,mean)
#中位数
apply(results,1,median)
par(mfrow = c(1,1))
boxplot(t(results))

```




